spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/word-count
    username: "postgres"
    password: "123456"
    hikari:
      connectionTimeout: 20000
      driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
#    profiles:
#      active: rest

